name: On Merge to prod - Clean cmd/main.go and Build

on:
  push:
    branches:
      - prod # Run on any push to prod (merge included)

jobs:
  clean-and-build:
    name: Clean cmd/main.go and Build Go Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # Use your Go version here

      - name: Remove godotenv block in cmd/main.go
        run: |
          echo "Removing godotenv block in cmd/main.go..."
          # Delete lines between the start comment and closing '}'
          sed -i '/Remove this code for Production/,/}/d' cmd/main.go

          echo "Updated cmd/main.go after cleanup:"
          cat cmd/main.go

      - name: Run go build
        run: |
          echo "Running go build..."
          go build ./...

      - name: Commit and push cleaned cmd/main.go
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add cmd/main.go
          git commit -m "Cleaned godotenv block after prod merge" || echo "No changes to commit"
          git push origin prod
